# Site settings
title: Shereef Younis
email: shereefeyounis@gmail.com
description: "A convenient space to showcase the projects and other work I completed during my college courses or on my own time."
baseurl: "https://shereefyounis.github.io/Shereef-Younis-Portfolio/"
url: "https://shereefyounis.github.io/Shereef-Younis-Portfolio/"

linkedin_username: Shereef Younis
github_username: shereefyounis

# Build settings
markdown: kramdown
